### ISSUE TITLE
Text labelled as "text_port" seems to be English instead

### ISSUE THREAD

**Issue by xrotwang** [UniversalDependencies/UD_Akuntsu-TuDeT#1]
E.g. here: https://github.com/UniversalDependencies/UD_Akuntsu-TuDeT/blob/afc41c85e24ac9b21224ad6aff2506624948024c/aqz_tudet-ud-test.conllu#L6

**Comment by LanguageStructure** [comment]
Daran müssen wir noch arbeiten
