### ISSUE TITLE
Cycles in sentence

### ISSUE THREAD

**Issue by wellington36** [UniversalDependencies/UD_Akuntsu-TuDeT#3]
@LanguageStructure, the sentence `sent_id = 0011.10` (on branch dev) has several looping problems between the tokens:

https://github.com/UniversalDependencies/UD_Akuntsu-TuDeT/blob/91398d34335d5f9927cdffdc370e9a949fc0cb84/aqz_tudet-ud-test.conllu#L1233

https://github.com/UniversalDependencies/UD_Akuntsu-TuDeT/blob/91398d34335d5f9927cdffdc370e9a949fc0cb84/aqz_tudet-ud-test.conllu#L1236

https://github.com/UniversalDependencies/UD_Akuntsu-TuDeT/blob/91398d34335d5f9927cdffdc370e9a949fc0cb84/aqz_tudet-ud-test.conllu#L1238

https://github.com/UniversalDependencies/UD_Akuntsu-TuDeT/blob/91398d34335d5f9927cdffdc370e9a949fc0cb84/aqz_tudet-ud-test.conllu#L1241

https://github.com/UniversalDependencies/UD_Akuntsu-TuDeT/blob/91398d34335d5f9927cdffdc370e9a949fc0cb84/aqz_tudet-ud-test.conllu#L1244

Among others in the same sentence.

**Comment by LanguageStructure** [comment]
Vou corrigir! Obrigado!
